name: test

on:
  push:
    branches:
      - main  # Replace with your branch name if different
  pull_request:
    branches:
      - main  # Replace with your branch name if different

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        
      - name: Display README.md content
        run: cat README.md

      - name: Determine status
        id: status
        run: echo "::set-output name=status::success"  # Assuming successful execution; replace with logic based on your actual checks
      
      - name: Send status payload
        if: ${{ always() }}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_DISPATCH_TOKEN }}
          event-type: pipeline-execution
          client-payload: '{"status": "${{ steps.status.outputs.status }}"}'
