name: test

on:
  push:
    branches:
      - main  # Replace with your branch name if different
  pull_request:
    branches:
      - main  # Replace with your branch name if different

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        
      - name: Display README.md content
        run: cat README.md
