name: Send Email Notification

on:
  repository_dispatch:
    types: pipeline-execution

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Payload
        run: |
          echo "Received payload:"
          echo "${{ toJson(github.event.client_payload) }}"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install sendgrid

      - name: Send Email Notification
        if: ${{ github.event.client_payload.status == 'success' }}
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          EMAIL_TO: mwasifali994@gmail.com  # Replace with the recipient email address
          EMAIL_SUBJECT: 'Pipeline Success Notification'
          EMAIL_BODY: 'Pipeline executed successfully.'
          EMAIL_FROM: wasifali.github@gmail.com  # Replace with the sender email address
        run: python send_email.py
