name: Send Email Notification

on:
  repository_dispatch:
    types: pipeline-execution

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Print Payload
        run: |
          echo "Received payload:"
          echo "${{ toJson(github.event.client_payload) }}"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install SendGrid
        run: pip install sendgrid

      - name: Send Email Notification
        if: ${{ github.event.client_payload.status == 'success' }}
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          EMAIL_TO: wasifali.github@gmail.com  # Replace with the recipient email address
          EMAIL_SUBJECT: 'Pipeline Success Notification'
          EMAIL_BODY: 'Pipeline executed successfully.'
          EMAIL_FROM: mwasifali994@gmail.com  # Replace with the sender email address
        run: |
          python -c "import os; \
          from sendgrid import SendGridAPIClient; \
          from sendgrid.helpers.mail import Mail; \
          message = Mail(from_email=os.getenv('EMAIL_FROM'), \
                         to_emails=os.getenv('EMAIL_TO'), \
                         subject=os.getenv('EMAIL_SUBJECT'), \
                         plain_text_content=os.getenv('EMAIL_BODY')); \
          try: \
              sg = SendGridAPIClient(os.getenv('SENDGRID_API_KEY')); \
              response = sg.send(message); \
              print(response.status_code); \
              print(response.body); \
              print(response.headers); \
          except Exception as e: \
              print(e.message)"
